#Declaring name
name: CI/CD pipeline


#It triggers when a pull request is done on main branch
on: 
  pull_request:
    branches:
      -main

env: 
  BRANCH: ${{github.head_ref}}
  cancel-in-progress: true

jobs:
  action:
    run-on: ubuntu-latest
    steps: 
    -name: check out changes
     uses: actions/checkout@v4

steps:
- uses: actions/checkout@v4
- uses: actions/setup-python@v5
  with:
    python-version: '3.12'   
- run: python my_script.py
