###############INTEGRATION##############

# name of the pipeline
name: Continuous Integration Workflow #can be orbitary

#Event is triggered when push || pull_request of branch main
on: 
  push: 
    branches: 
      - main
  pull_request:
    branches:
      - main
  #Gives a Manual option to trigger the Pipeline
  workflow_dispatch:

#list of jobs
jobs: 
    first-job:  #can be orbitary
      #The Operating System
        runs-on: ubuntu-latest
        steps:
          #Utlizing the latest actions// V4 is the version
            - name: Checkout actions
              uses: actions/checkout@v4 
            - run: echo "The ${{ github.repository }} repository has been cloned "

    second-job:  #can be orbitary
        runs-on: ubuntu-latest
        #needs => The step mention must be completed to start the current step
        needs: first-job
        #IF is added to run rest only when step mentioned must complete successfully
        steps:
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.12'
            - name: Display Python version
              run: python -c "import sys; print(sys.version)"
         #   - name: Install Dependecies
         #     run: |
         #         python -m pip install --upgrade pip
         #         pip install -r requirements.txt

    third-job : 
        runs-on: ubuntu-latest
        needs: [first-job, second-job]
        env:
          Greeting: Hello
        steps:
            - name: "Say Hello it's Monday"
              run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
              env:
                First_Name: python

     
