name: CICD TEST

on: [push, pull_request]
jobs: 

    first-job:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout actions
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.12'
           # - name: Install dependencies
            #  run : |
             #   python -m pip install --upgrade pip 
              #  pip install -r requirements.txt
           # - name: Run Tests
            #  run : |
             #   pytest
